
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "TestGame_common.h"
namespace TestGame {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_SendItems,
               
		Rmi_SendPlayerInfo,
               
		Rmi_Move,
               
		Rmi_WhoAmI,
               
		Rmi_WhoYouAre,
	};

	int g_RmiIDListCount = 5;

}





