 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace TestGame
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SendItemSet = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID SendPlayer = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID Move = (Nettention.Proud.RmiID)1000+3;
			public const Nettention.Proud.RmiID WhoAmI = (Nettention.Proud.RmiID)1000+4;
			public const Nettention.Proud.RmiID WhoYouAre = (Nettention.Proud.RmiID)1000+5;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SendItemSet,
			SendPlayer,
			Move,
			WhoAmI,
			WhoYouAre,
		};
	}
}






				 
